security:
  key: somerandomkeywhichislongenoughtoalignwiththejwtspecification

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pokedex
    username: "admin"
    password: "admin"

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG